spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: jerry-service

server:
  port: ${PORT:8080}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

security:
  jwt:
    secret: ${JWT_SECRET:jerry-general}
    expiration: ${JWT_EXP_SECONDS:3600}

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME:}
    token: ${TELEGRAM_BOT_TOKEN:}
    chat-id: ${TELEGRAM_CHAT_ID:}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
