spring:
  application:
    name: jerry-service

  datasource:
    # Prefer env overrides on Render. If you set SPRING_DATASOURCE_URL, Spring will use it.
    # Otherwise this default works for your Render Postgres:
    url: jdbc:postgresql://dpg-d2ndpj75r7bs73ff00q0-a.oregon-postgres.render.com:5432/jerrydb?sslmode=require
    username: ${DB_USER:jerrydb}
    password: ${DB_PASSWORD:5wVD2lAxjJlxo6vQlARydPjKoqIITqaT}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update              # change to validate/none in prod if schema is managed
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: ${PORT:8080}                # Render injects PORT
  address: 0.0.0.0
  forward-headers-strategy: framework
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

# Custom app configs (bind with @ConfigurationProperties)
security:
  jwt:
    secret: ${JWT_SECRET:change-me}
    expiration: ${JWT_EXP_SECONDS:3600}

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME:}
    token: ${TELEGRAM_BOT_TOKEN:}
    webhook-url: ${TELEGRAM_WEBHOOK_URL:}

---
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
